# generated by datamodel-codegen:
#   filename:  dashboard.v1.json
#   command:   datamodel-codegen --input packages/dashboard-spec/schema/dashboard.v1.json --input-file-type jsonschema --output-model-type pydantic_v2.BaseModel --target-python-version 3.12 --use-standard-collections --use-union-operator --use-annotated --field-constraints --enum-field-as-literal all --use-double-quotes --disable-timestamp --enable-command-header --formatters ruff-format ruff-check

from __future__ import annotations

from typing import Annotated, Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Name(RootModel[str]):
    root: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_]*$")]


class ModelKey(RootModel[str]):
    root: Annotated[str, Field(pattern="^[A-Za-z_][A-Za-z0-9_]*(\\.[A-Za-z_][A-Za-z0-9_]*)*$")]


class Identifier(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-z][a-z0-9_]*$")]


class Slug(RootModel[str]):
    root: Annotated[str, Field(pattern="^[a-z0-9][a-z0-9-]*$")]


class Binding(RootModel[str]):
    root: Annotated[str, Field(pattern="^\\$filters\\.[a-z][a-z0-9_]*$")]


class IsoDate(RootModel[str]):
    root: Annotated[str, Field(pattern="^\\d{4}-\\d{2}-\\d{2}$")]


class Scalar1(RootModel[str]):
    root: Annotated[str, Field(max_length=1024)]


class Scalar(RootModel[Scalar1 | float | bool]):
    root: Scalar1 | float | bool


class NameArray(RootModel[list[Name]]):
    root: Annotated[list[Name], Field(max_length=50)]


class Metadata(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    slug: Slug
    title: Annotated[str, Field(min_length=1)]
    description: str | None = None
    owner: str | None = None
    tags: list[str] | None = None


class Layout(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    columns: Annotated[int | None, Field(ge=1, le=24)] = 12


class Default(RootModel[list[Scalar]]):
    root: Annotated[list[Scalar], Field(max_length=50)]


class DimensionFilter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["dimension"] | None = None
    name: Identifier
    dimension: Name
    default: Scalar | Default | None = None


class Default1(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class PeriodFilter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["period"]
    name: Identifier
    default: Default1 | None = None


class Position(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    x: Annotated[int, Field(ge=0)]
    y: Annotated[int, Field(ge=0)]
    w: Annotated[int, Field(ge=1)]
    h: Annotated[int, Field(ge=1)]


class Provenance(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    show: bool | None = True


class Value(RootModel[list[Scalar]]):
    root: Annotated[list[Scalar], Field(max_length=50)]


class QueryFilter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    column: Name
    operator: Literal["eq", "neq", "gt", "lt", "gte", "lte", "in", "like", "is_null", "is_not_null"]
    value: Scalar | Value | None = None


class Query(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    model: ModelKey
    metrics: NameArray | None = None
    group_by: NameArray | None = None
    filters: Annotated[list[QueryFilter] | None, Field(max_length=50)] = None
    date_from: IsoDate | None = None
    date_to: IsoDate | None = None
    period: Annotated[str | None, Field(min_length=1)] = None


class Format(
    RootModel[dict[str, Literal["number", "integer", "percent", "currency_eur", "currency_usd"]]]
):
    root: dict[str, Literal["number", "integer", "percent", "currency_eur", "currency_usd"]]


class KpiViz(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["kpi"]
    metric: Name
    format: Format | None = None


class TableViz(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["table"]
    columns: NameArray | None = None
    format: Format | None = None


class BarViz(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["bar"]
    x: Name
    series: Annotated[list[Name], Field(min_length=1)]
    format: Format | None = None


class LineViz(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["line"]
    x: Name
    series: Annotated[list[Name], Field(min_length=1)]
    format: Format | None = None


class Viz(RootModel[KpiViz | TableViz | BarViz | LineViz]):
    root: KpiViz | TableViz | BarViz | LineViz


class GlobalFilter(RootModel[DimensionFilter | PeriodFilter]):
    root: DimensionFilter | PeriodFilter


class Tile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Identifier
    title: str | None = None
    description: str | None = None
    position: Position
    query: Query
    viz: Viz
    provenance: Provenance | None = None
    ignore_filters: list[Identifier] | None = None


class Spec(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    layout: Layout | None = None
    filters: list[GlobalFilter] | None = None
    tiles: Annotated[list[Tile], Field(min_length=1)]


class DashboardAsYamlV1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    apiVersion: Literal["skifer-board/v1"]
    kind: Literal["Dashboard"]
    metadata: Metadata
    spec: Spec
